version: "3.8"
services:
  gwallet_backend:
    build: .
    container_name: gwallet_backend
    networks:
      - gwallet-networks
    ports:
      - 3006:3006
    env_file: ./.env
    volumes:
      - .:/app 
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    networks:
      - backend
    environment:
      - DB_HOST = localhost
      - DB_USER = root
      - DB_PASSWORD = lahat2002
      - DB_NAME = gwallet_database
  ports:
    - 3307:3306
  networks:
    - dbconnect
networks:
  dbconnect:
    driver: bridge